apiVersion: v1
kind: Service
metadata:
  name: quarkus
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: quarkus
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 8081
  selector:
    app: quarkus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quarkus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus
        version: v1
    spec:
      containers:
        - name: quarkus
#          image: eu.gcr.io/YOUR_PROJECT/quarkus:latest
          image: quarkus:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: privatekey
              mountPath: "/etc/private_key"
              readOnly: true
            - name: publickey
              mountPath: "/etc/public_key"
              readOnly: true
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: QUARKUS_HTTP_PORT
              value: "8081"
            - name: QUARKUS_PROFILES
              value: auth
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DATABASE
              value: docker
            - name: PRIVATE_KEY_PATH
              value: /etc/private_key/dummy_privateKey.pem
            - name: PUBLIC_KEY_PATH
              value: /etc/public_key/dummy_publicKey.pem
            - name: QUARKUS_METRICS_PATH
              value: /actuator
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8081
            initialDelaySeconds: 200
            periodSeconds: 5
      volumes:
        - name: publickey
          secret:
            secretName: publickey
        - name: privatekey
          secret:
            secretName: privatekey
